### ISSUE TITLE
Writing Bug-Free Code in Haskell

### ISSUE THREAD

**Issue by thenaesh** [nus-oss/lightningtalks#12]
**Synopsis:**

A discussion of the benefits of Haskell in a software engineering context, focusing on the benefits brought by the functional nature of the language, the type system, and purity.

[Accompanying Slides](https://docs.google.com/presentation/d/1VbXCMjFZtZgRQPvAKb9K4h9OX9COZqt0M3PxTnBERvQ/edit?usp=sharing)

**Comment by damithc** [comment]
@thenaesh majority of the audience will get something out of listening to your talk? i.e. is this something they will value knowing?

**Comment by thenaesh** [comment]
@damithc Oops, I forgot to mention the purpose of the talk.

I think the audience will get something out of this because functional purity makes it easy to write highly-testable (and often completely bug-free) code. Perhaps I could make software correctness and testing the focus of the talk, scrapping the part on free theorems and using a more concrete example to show how the type system and enforced purity prevents edge cases from occurring?

(The part on concurrency/parallelism is a bonus, and I will just mention it in passing..)
