### ISSUE TITLE
The Ops in DevOps: what every dev should know

### ISSUE THREAD

**Issue by whipermr5** [nus-oss/lightningtalks#13]
### Synopsis

*   DevOps - a mindset, not a role
*   Culture
*   Automation
*   Metrics

[Slides](https://github.com/nus-oss/lightningtalks/files/753803/devops.pptx)

**Comment by damithc** [comment]
DevOps is one of those terms thrown around a lot but many don't know exactly what it means (although everybody has a rough idea of what area it covers). It would be nice if your talk clears it up.
