### ISSUE TITLE
Strong and Weak in Swift

### ISSUE THREAD

**Issue by ablyx** [nus-oss/lightningtalks#15]
**Synopsis:**

Strong and Weak in Swift

1. Automatic Reference Counter
2. Strong Reference Cycle
3. Resolving Strong Reference Cycles
4. ViewController example
5. Conclusion

Slides are here at https://docs.google.com/presentation/d/14bLUoBH0SYfuMB7pM1K8QioGoueflNx5-XGGVqFD3hQ/edit?usp=sharing

**Comment by damithc** [comment]
Given the short time, you may not be able to teach Swift, not even basics. Instead, you can cherry-pick the cool stuff (even advanced features) to showcase, with the objective of convincing the audience to learn Swift.
