### ISSUE TITLE
How Gradle can help mange your project

### ISSUE THREAD

**Issue by MightyCupcakes** [nus-oss/lightningtalks#18]
**Synopsis**

1. What is gradle
2. How gradle makes managing your project builds and dependencies easier

Slides are avaliable [here](http://www.comp.nus.edu.sg/~gohydj/GradleBuildAutomation.pptx)

**Comment by damithc** [comment]
@MightyCupcakes most of the audience are aware of Gradle (because it is used in CS2103 since last semester) but probably are unaware of its power; something you can take into account when selecting the talk content.
