### ISSUE TITLE
Why Python?

### ISSUE THREAD

**Issue by samsontmr** [nus-oss/lightningtalks#2]
**Synopsis**

* Why you should learn Python

Here's the link to my slides: [Why Python?](https://docs.google.com/presentation/d/1GB_ghhWGbOY1qdQ25v96KbiYrhn-m3gYo7ewJ6K9iNw/edit?usp=sharing)

I've also included links in the speaker notes of some slides for further reading. Let me know if you can't see them!

**Comment by samsontmr** [comment]
@damithc  I might be shrinking this to just Why Python? due to the time constraint

**Comment by damithc** [comment]
> I might be shrinking this to just Why Python? due to the time constraint

Sure. Change issue title if you want to change talk title.

**Comment by samsontmr** [comment]
Here's the link to my slides: [Why Python?](https://docs.google.com/presentation/d/1GB_ghhWGbOY1qdQ25v96KbiYrhn-m3gYo7ewJ6K9iNw/edit?usp=sharing)

I've also included links in the speaker notes of some slides for further reading. Let me know if you can't see them!
