### ISSUE TITLE
C#: Think with LINQ

### ISSUE THREAD

**Issue by jamos-tay** [nus-oss/lightningtalks#28]
PUNCH:

* Programmers like you and me work with data everyday. Here’s how you can make it more convenient.

WIIFY:

* For those who use C#: Here’s a useful library you may be unaware of that does data manipulation efficiently
* For those who don’t use C#: This talk displays a unique and useful feature of C# and shows why C# is a good language to learn

Promise:

* Know: That LINQ exists, what LINQ does, why it is useful and how it can benefit you.
* Believe: LINQ is a useful tool. It is better to use LINQ over ordinary data processing methods. I can benefit from using LINQ in my programs.
* Do: Apply what they have learnt when/if they use C#.

Summary:

* LINQ is a useful library and is one of C#’s best selling points, C# programmers should be aware that it exists and take advantage of it in their work.

Points + support:

What is LINQ:
*  Stands for Language Integrated Query
* Built in library unique to C#
* SQL like syntax for querying various datasets

Why LINQ is good:
* LINQ is convenient:
  * Achieves the same result with less lines of code
  * Wide variety of use cases
  * Easy to read
* LINQ is easy to learn:
  * Builds on what people already know
  * Syntax similar to SQL
  * Easily understood – almost English like syntax
* In contrast with other languages:
  * More readable syntax
  * More functionality

How it can benefit you:
* Know that it exists and use it. (I find C# users tend to be unaware of LINQ; probably because C# is uncommon and many C# users come from Java. A lot of online tutorials leave out LINQ as a topic)
* Saves time and energy and allows you to write more readable and maintainable code.

**Comment by jamos-tay** [comment]
Slides: 
[LINQ.pptx](https://github.com/nus-oss/lightningtalks/files/819123/LINQ.pptx)

Code snippets have a textbox offscreen with their content.

**Comment by Neurrone** [comment]
Thanks @jamos-tay :)
