### ISSUE TITLE
Introduction to GraphQL

### ISSUE THREAD

**Issue by li-kai** [nus-oss/lightningtalks#3]
**Synopsis:**

A comfortable introduction to GraphQL and what it means for the future of web services.

1. What is GraphQL exactly? Does it actually has anything to do with graphs?
2. Pros and Cons versus the all popular REST
3. A quick dive into why/how GraphQL works

**Comment by damithc** [comment]
I assume 'Why should you care about GraphQL' will be captured in the WIIFY part of the opening segment.

**Comment by li-kai** [comment]
The slides are here:
https://li-kai.github.io/lightning-talks/

Press `s` to see the notes.
