### ISSUE TITLE
Neural Networks: How do they work?

### ISSUE THREAD

**Issue by Kenneth-LJS** [nus-oss/lightningtalks#5]
**Synopsis**:

A quick introduction to neural networks, and then diving straight into why they work.

1. How do neural networks work?
2. The building blocks of neural networks
3. Application case study

**Comment by damithc** [comment]
I would be interested to know where Neural Networks fit into the whole AI landscape

**Comment by Kenneth-LJS** [comment]
My slides are available [here](https://github.com/nus-oss/lightningtalks/files/724236/Slides.pdf)
