### ISSUE TITLE
Regexing Responsibly

### ISSUE THREAD

**Issue by jamos-tay** [nus-oss/lightningtalks#6]
**Synopsis:**

A brief look at the underlying mechanisms of regular expressions, and the dangers of using it inappropriately.

1. How the regex algorithm works
2. 2-3 case studies of possible bad scenarios
3. Summary of learning points, and what to do/avoid in future

**Comment by damithc** [comment]
Don't forget to talk about benefits of regex. It's better if your main goal is to convince audience to learn regex.

**Comment by jamos-tay** [comment]
The slides are available [here](https://github.com/nus-oss/lightningtalks/files/753021/Regexing.Responsibly.pptx)
